// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ezeqixtxqahfldgkwbna.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6ZXFpeHR4cWFoZmxkZ2t3Ym5hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMDM4MDYsImV4cCI6MjA3Mzc3OTgwNn0.xkTlt99dqAbraRFltbCH5_nInZca0TMO9FBKiml58GM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});